import type { PrayerConnectRequest } from "./types";
import type { CommunityPrayerResponses } from "./communityResponses";

const PERMISSIONS = [
  "allow-public-prayers",
  "allow-public-video-prayers",
  "allow-private-messages",
  "allow-private-video-prayers",
  "allow-encouragement",
  "allow-sharing",
];

function daysAgo(days: number) {
  return new Date(Date.now() - days * 86_400_000).toISOString();
}

export const MOCK_PRAYER_REQUESTS: PrayerConnectRequest[] = [
  {
    id: "mock-prayer-health-1",
    userId: "mock-user-1",
    displayName: "Maria Lopez",
    avatarUrl: null,
    title: "Healing after surgery",
    body: "Please pray for complete recovery after my knee replacement. I am trusting God for strength during physical therapy.",
    locationLabel: "Phoenix, Arizona",
    category: "health",
    categoryLabel: "Health",
    mediaKind: "photo",
    imageUrl: "/images/journey/03-reflection-room-desktop.png",
    videoUrl: null,
    thumbnailUrl: null,
    prayerStatus: "active",
    createdAt: daysAgo(1),
    lat: 33.4484,
    lng: -112.074,
    distanceMiles: null,
    prayingCount: 42,
    encouragementCount: 11,
    responseCount: 3,
    isAnonymous: false,
    isUrgent: false,
    topics: ["health", ...PERMISSIONS],
  },
  {
    id: "mock-prayer-family-2",
    userId: "mock-user-2",
    displayName: "James Carter",
    avatarUrl: null,
    title: "Reconciliation in our home",
    body: "Our family has been distant for months. Pray for humility, forgiveness, and peace around our dinner table again.",
    locationLabel: "Scottsdale, Arizona",
    category: "family",
    categoryLabel: "Family",
    mediaKind: "text",
    imageUrl: null,
    videoUrl: null,
    thumbnailUrl: null,
    prayerStatus: "active",
    createdAt: daysAgo(2),
    lat: 33.4942,
    lng: -111.9261,
    distanceMiles: null,
    prayingCount: 28,
    encouragementCount: 6,
    responseCount: 1,
    isAnonymous: false,
    isUrgent: false,
    topics: ["family", ...PERMISSIONS],
  },
  {
    id: "mock-prayer-deliverance",
    userId: "mock-user-3",
    displayName: "Anonymous",
    avatarUrl: null,
    title: "Breakthrough from bondage",
    body: "I am asking the community to stand with me for deliverance from patterns that keep pulling me back. Pray for freedom and clarity.",
    locationLabel: "Tempe, Arizona",
    category: "other",
    categoryLabel: "Prayer for deliverance",
    mediaKind: "text",
    imageUrl: null,
    videoUrl: null,
    thumbnailUrl: null,
    prayerStatus: "active",
    createdAt: daysAgo(3),
    lat: 33.4255,
    lng: -111.94,
    distanceMiles: null,
    prayingCount: 61,
    encouragementCount: 19,
    responseCount: 5,
    isAnonymous: true,
    isUrgent: true,
    topics: ["other", "Prayer for deliverance", "urgent", ...PERMISSIONS],
  },
  {
    id: "mock-prayer-answered",
    userId: "mock-user-4",
    displayName: "Hannah Kim",
    avatarUrl: null,
    title: "Job provision — answered",
    body: "Thank you for praying. I received an offer after months of searching. Grateful for every person who interceded.",
    locationLabel: "Mesa, Arizona",
    category: "faith",
    categoryLabel: "Faith",
    mediaKind: "photo",
    imageUrl: "/images/journey/04-keep-going-desktop.png",
    videoUrl: null,
    thumbnailUrl: null,
    prayerStatus: "answered",
    createdAt: daysAgo(14),
    lat: 33.4152,
    lng: -111.8315,
    distanceMiles: null,
    prayingCount: 88,
    encouragementCount: 34,
    responseCount: 12,
    isAnonymous: false,
    isUrgent: false,
    topics: ["faith", ...PERMISSIONS],
  },
  {
    id: "mock-prayer-video-1",
    userId: "mock-user-5",
    displayName: "Daniel Wright",
    avatarUrl: null,
    title: "Pray for my daughter's courage",
    body: "She starts a new school next week and is anxious. We recorded a short video so you can see her heart.",
    locationLabel: "Chandler, Arizona",
    category: "children",
    categoryLabel: "Children",
    mediaKind: "video",
    imageUrl: null,
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    thumbnailUrl: "/images/feed/freedom-feed-hero-final.webp",
    prayerStatus: "active",
    createdAt: daysAgo(4),
    lat: 33.3062,
    lng: -111.8413,
    distanceMiles: null,
    prayingCount: 53,
    encouragementCount: 14,
    responseCount: 4,
    isAnonymous: false,
    isUrgent: false,
    topics: ["children", ...PERMISSIONS],
  },
  {
    id: "mock-prayer-saved",
    userId: "mock-user-6",
    displayName: "Elena Ruiz",
    avatarUrl: null,
    title: "Wisdom for a major decision",
    body: "I need discernment about relocating for work while caring for my aging parents.",
    locationLabel: "Glendale, Arizona",
    category: "work",
    categoryLabel: "Work",
    mediaKind: "text",
    imageUrl: null,
    videoUrl: null,
    thumbnailUrl: null,
    prayerStatus: "active",
    createdAt: daysAgo(5),
    lat: 33.5387,
    lng: -112.186,
    distanceMiles: null,
    prayingCount: 17,
    encouragementCount: 4,
    responseCount: 0,
    isAnonymous: false,
    isUrgent: false,
    topics: ["work", ...PERMISSIONS],
  },
  {
    id: "mock-prayer-long",
    userId: "mock-user-7",
    displayName: "Pastor Aaron Mills",
    avatarUrl: null,
    title:
      "Pray for our church plant as we launch weekly gatherings in a neighborhood that has never had a gospel-centered community",
    body: "We are stepping out in faith with a small team, limited resources, and a deep conviction that God can transform this corridor. Pray for favor with city leaders, volunteers, childcare, worship, and hearts open to Jesus.",
    locationLabel: "Peoria, Arizona",
    category: "ministry",
    categoryLabel: "Ministry",
    mediaKind: "photo",
    imageUrl: "/images/journey/01-journey-hero-desktop.png",
    videoUrl: null,
    thumbnailUrl: null,
    prayerStatus: "active",
    createdAt: daysAgo(6),
    lat: 33.5806,
    lng: -112.2374,
    distanceMiles: null,
    prayingCount: 74,
    encouragementCount: 22,
    responseCount: 8,
    isAnonymous: false,
    isUrgent: false,
    topics: ["ministry", ...PERMISSIONS],
  },
  {
    id: "mock-prayer-short",
    userId: "mock-user-8",
    displayName: "Anonymous",
    avatarUrl: null,
    title: "Peace tonight",
    body: "Anxiety is high. Pray for rest.",
    locationLabel: "Phoenix, Arizona",
    category: "emotional",
    categoryLabel: "Emotional well-being",
    mediaKind: "text",
    imageUrl: null,
    videoUrl: null,
    thumbnailUrl: null,
    prayerStatus: "active",
    createdAt: daysAgo(0.2),
    lat: 33.45,
    lng: -112.07,
    distanceMiles: null,
    prayingCount: 9,
    encouragementCount: 2,
    responseCount: 0,
    isAnonymous: true,
    isUrgent: false,
    topics: ["emotional", "anonymous", ...PERMISSIONS],
  },
  {
    id: "mock-prayer-finances",
    userId: "mock-user-9",
    displayName: "Tanya Brooks",
    avatarUrl: null,
    title: "Provision for rent",
    body: "Single mom here. Pray for provision this month and for my kids to feel secure.",
    locationLabel: "Gilbert, Arizona",
    category: "finances",
    categoryLabel: "Finances",
    mediaKind: "photo",
    imageUrl: "/images/feed/freedom-feed-composer-wide-v2.webp",
    videoUrl: null,
    thumbnailUrl: null,
    prayerStatus: "active",
    createdAt: daysAgo(7),
    lat: 33.3528,
    lng: -111.789,
    distanceMiles: null,
    prayingCount: 36,
    encouragementCount: 9,
    responseCount: 2,
    isAnonymous: false,
    isUrgent: false,
    topics: ["finances", ...PERMISSIONS],
  },
  {
    id: "mock-prayer-grief",
    userId: "mock-user-10",
    displayName: "Robert Hale",
    avatarUrl: null,
    title: "Comfort after loss",
    body: "My brother passed suddenly. Pray for our family as we grieve and plan his memorial.",
    locationLabel: "Surprise, Arizona",
    category: "grief",
    categoryLabel: "Grief",
    mediaKind: "text",
    imageUrl: null,
    videoUrl: null,
    thumbnailUrl: null,
    prayerStatus: "active",
    createdAt: daysAgo(8),
    lat: 33.6292,
    lng: -112.368,
    distanceMiles: null,
    prayingCount: 49,
    encouragementCount: 18,
    responseCount: 6,
    isAnonymous: false,
    isUrgent: false,
    topics: ["grief", ...PERMISSIONS],
  },
  {
    id: "mock-prayer-addiction",
    userId: "mock-user-11",
    displayName: "Chris Nguyen",
    avatarUrl: null,
    title: "Strength in early recovery",
    body: "Day 12 sober. Pray I keep showing up to meetings and stay honest with my sponsor.",
    locationLabel: "Phoenix, Arizona",
    category: "addiction",
    categoryLabel: "Addiction",
    mediaKind: "photo",
    imageUrl: "/images/journey/02-testimony-map-background-desktop.png",
    videoUrl: null,
    thumbnailUrl: null,
    prayerStatus: "active",
    createdAt: daysAgo(9),
    lat: 33.46,
    lng: -112.08,
    distanceMiles: null,
    prayingCount: 31,
    encouragementCount: 8,
    responseCount: 1,
    isAnonymous: false,
    isUrgent: true,
    topics: ["addiction", "urgent", ...PERMISSIONS],
  },
  {
    id: "mock-prayer-relationships",
    userId: "mock-user-12",
    displayName: "Priya Shah",
    avatarUrl: null,
    title: "Restoration with a friend",
    body: "A misunderstanding damaged a close friendship. Pray for humility on both sides.",
    locationLabel: "Phoenix, Arizona",
    category: "relationships",
    categoryLabel: "Relationships",
    mediaKind: "text",
    imageUrl: null,
    videoUrl: null,
    thumbnailUrl: null,
    prayerStatus: "active",
    createdAt: daysAgo(10),
    lat: 33.44,
    lng: -112.06,
    distanceMiles: null,
    prayingCount: 14,
    encouragementCount: 3,
    responseCount: 0,
    isAnonymous: false,
    isUrgent: false,
    topics: ["relationships", ...PERMISSIONS],
  },
  {
    id: "mock-prayer-community",
    userId: "mock-user-13",
    displayName: "Neighborhood Watch",
    avatarUrl: null,
    title: "Safety for our block",
    body: "Recent break-ins have neighbors on edge. Pray for peace and wise community action.",
    locationLabel: "Phoenix, Arizona",
    category: "community",
    categoryLabel: "Community",
    mediaKind: "photo",
    imageUrl: "/images/journey/03-reflection-room-mobile.png",
    videoUrl: null,
    thumbnailUrl: null,
    prayerStatus: "active",
    createdAt: daysAgo(11),
    lat: 33.452,
    lng: -112.09,
    distanceMiles: null,
    prayingCount: 22,
    encouragementCount: 5,
    responseCount: 1,
    isAnonymous: false,
    isUrgent: false,
    topics: ["community", ...PERMISSIONS],
  },
];

export const MOCK_SAVED_STORY_IDS = ["mock-prayer-saved", "mock-prayer-deliverance"];

export function getMockCommunityResponses(
  storyId: string
): CommunityPrayerResponses | null {
  if (storyId !== "mock-prayer-video-1") return null;

  return {
    totalCount: 2,
    written: [],
    video: [
      {
        id: "mock-video-response-1",
        videoUrl:
          "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        signedVideoUrl:
          "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        thumbnailUrl: "/images/feed/freedom-feed-hero-final.webp",
        signedThumbnailUrl: "/images/feed/freedom-feed-hero-final.webp",
        authorUserId: "mock-responder-1",
        author: {
          id: "mock-responder-1",
          displayName: "Sarah M.",
          avatarUrl: null,
          isAnonymous: false,
        },
        createdAt: daysAgo(1),
        status: "approved",
      },
      {
        id: "mock-video-response-2",
        videoUrl:
          "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        signedVideoUrl:
          "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        thumbnailUrl: "/images/journey/03-reflection-room-desktop.png",
        signedThumbnailUrl: "/images/journey/03-reflection-room-desktop.png",
        authorUserId: "mock-responder-2",
        author: {
          id: "mock-responder-2",
          displayName: "Michael T.",
          avatarUrl: null,
          isAnonymous: false,
        },
        createdAt: daysAgo(2),
        status: "approved",
      },
    ],
  };
}
